### ISSUE TITLE
Add usage example

### ISSUE THREAD

**Issue by miguelprada** [tecnalia-medical-robotics/wrench_marker#1]
Add an example node which listens to `geometry_msgs/Wrench` messages and publishes the wrench as a marker.
- [x] define node API (topics/params)
- [x] write node
- [x] usage in README

**Comment by miguelprada** [comment]
@aremazeilles Could you have a look at `wrench_marker_publisher` and see if it's useful for you?

**Comment by aremazeilles** [comment]
I´ll check it in the afternoon an tell you then
