### ISSUE TITLE
geometry_msg/Wrench vs geometry_msg/WrenchStamped

### ISSUE THREAD

**Issue by aremazeilles** [tecnalia-medical-robotics/wrench_marker#2]
in example program, a geometry_msg/Wrench is expected, but the optoforce_node publishes a  geometry_msg/WrenchStamped

What would be the nicest way to adjust this in your opinion?

**Comment by miguelprada** [comment]
I suspected this could be the case. Give me some time to prepare a proposal, since I think it's best to handle this properly at the level of the library.

**Comment by miguelprada** [comment]
Believe, this is closed by #3.
